# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/maxwell',
                'doc_host': 'https://aetb.github.io',
                'git_url': 'https://github.com/aetb/maxwell',
                'lib_path': 'maxwell'},
  'syms': {'maxwell.core': {'maxwell.core.foo': ('core.html#foo', 'maxwell/core.py')}}}
